TwinePlatform/twine-visitor

react-backend/client/public/index.html, react-backend/client/src/components/main_copy.js
login component now re-renders once the code is scanned
=> #6 when code scanned, state updated in React

react-backend/.eslintrc.json, react-backend/bin/www, react-backend/client/.eslintrc.json, react-backend/client/package-lock.json, react-backend/client/package.json, react-backend/client/public/index.html, react-backend/client/public/manifest.json, react-backend/client/src/App.css, react-backend/client/src/App.js, react-backend/client/src/components/button.js, react-backend/client/src/components/input.js, react-backend/client/src/components/main_copy.js, react-backend/client/src/components/privacy.js, react-backend/client/src/components/privacy_copy.js, react-backend/client/src/components/select.js, react-backend/client/src/registerServiceWorker.js, react-backend/package-lock.json, react-backend/package.json, react-backend/routes/index.js, react-backend/routes/users.js
Just tidied all of the files up a bit with eslint-airbnb
=> Justtidyingup

react-backend/client/src/components/main_copy.js, react-backend/client/src/components/purposeButton.js
=> added purposeButton component

react-backend/app.js, react-backend/client/public/index.html, react-backend/client/src/App.js, react-backend/client/src/components/main.js, react-backend/client/src/components/qrcode.js, react-backend/client/src/components/qrprivacy.js, react-backend/public/javascripts/instascan.js, react-backend/routes/getUsername.js, react-backend/routes/qrgenerator.js
=> Switch between privacy components work, user full name is displayed on log in page

package-lock.json, react-backend/app.js, react-backend/client/src/App.css, react-backend/client/src/components/main.js, react-backend/database/queries/getUserAlreadyExists.js, react-backend/routes/userchecker.js
The database is now checked for a combination of username and email.
=> #12 integrated a user details database check into the flow

react-backend/client/src/App.js, react-backend/client/src/components/main.js, react-backend/client/src/components/qrcode.js, react-backend/client/src/components/qrerror.js, react-backend/routes/getUsername.js
#6 If the user's QR code returns a non-database request, the user is redirected to a view allowing them to choose new options.
=> QR error handling

react-backend/client/src/components/main.js
=> Fixed error messages and database check for existing name and email

react-backend/database/dbBuild.sql, react-backend/routes/userchecker.js
=> Fixed some database errors #24

react-backend/client/src/App.css
=> more css styling

react-backend/client/src/App.css, react-backend/client/src/components/admin/homeAdmin.js, react-backend/database/queries/getAllUsers.js
=> admin page updated

react-backend/client/public/manifest.json
=> Fixing PWA manifest.json

react-backend/client/src/App.css, react-backend/client/src/components/visitors/homeVisitor.js, react-backend/client/src/components/visitors/main.js, tests/tests.js
Added the data policy link to the visitor home page
=> Datapolicy

.travis.yml, react-backend/app.js, react-backend/client/src/App.js, react-backend/client/src/components/authentication/logincb.js, react-backend/client/src/components/authentication/signupcb.js, react-backend/database/dbBuild.sql, react-backend/database/queries/CBqueries/putCBData.js, react-backend/database/queries/getCBAlreadyExists.js, react-backend/database/queries/getCBlogindetailsvalid.js, react-backend/functions/cbhash.js, react-backend/functions/sendCBemail.js, react-backend/routes/cbauthentication/checkCB.js, react-backend/routes/cbauthentication/checkCBlogin.js, react-backend/routes/cbauthentication/registerCB.js
relates to issues #76, #77, #91 
The code is super messy, but it's functional :) We will go back and refactor it next week.
=> CB login & signup

react-backend/client/src/components/visitors/homeVisitor.js, react-backend/routes/cbauthentication/CBPasswordResetInstigator.js
Added "Welcome visitor!" message to homeVisitor.js component, put date.now() inside a function
=> Fixed Expired Date.now() bug

react-backend/client/src/components/authentication/logincb.js, react-backend/client/src/components/authentication/newPassword.js, react-backend/client/src/components/authentication/pswdresetcb.js, react-backend/client/src/components/authentication/signupcb.js, react-backend/client/src/components/errors.js, react-backend/client/src/components/visitors/main.js
relates to issue #91 
Removed error messages from main.js, signupcb.js, pswdresetcb.js, newPassword.js, logincb.js and added them into new file "errors.js";
replaced "else if" statements for error messages with "switch/case" ones (apart from logincb.js)
=> Error messages refactoring

react-backend/client/src/App.js, react-backend/client/src/components/InternalServerError.js, react-backend/client/src/components/admin/homeAdmin.js, react-backend/client/src/components/authentication/logincb.js, react-backend/client/src/components/authentication/newPassword.js, react-backend/client/src/components/authentication/pswdresetcb.js, react-backend/client/src/components/authentication/signupcb.js, react-backend/client/src/components/visitors/main.js, react-backend/client/src/components/visitors/qrcode.js, react-backend/frontEndRoutes.js, react-backend/functions/hash.js, react-backend/functions/sendCBemail.js, react-backend/routes/cbauthentication/checkCBlogin.js, react-backend/routes/cbauthentication/checkPassword.js, react-backend/routes/cbauthentication/registerCB.js, react-backend/routes/checkUser.js, react-backend/routes/postActivity.js, react-backend/routes/qrgenerator.js
added res.status(500).send(err) to backend files where this was missing,
added error handling on the front end for 500
relates to #17
=> added 500 error handling on the front end, relates to issue #17

react-backend/client/src/components/admin/homeAdmin.js, react-backend/client/src/components/visitors/homeVisitor.js
a minor fix to improve user experience: added reset button to homeAdmin.js
=> added resetbutton to homeAdmin.js

react-backend/functions/sendCBemail.js
changed postmark template for cb admin email
=> changed postmark template for cb admin email

react-backend/client/src/components/visitors/main.js
The case in main.js was expecting `false` when actually it was a string of false coming from the server.
Also prettiers main.js so the diffs are a little larger.
#139
=> fixes user sign in bug

react-backend/database/queries/activitiesForToday.js
Refactors the _activities for today_ query to be more functional and swaps the pg query to a promise.
#127
=> Activities for today refactor

package-lock.json, package.json, react-backend/.eslintrc.json, react-backend/client/.eslintrc.json, react-backend/client/package-lock.json, react-backend/client/package.json
changes eslint config so it can work with prettier. Also adds early returns and jsx within .js files. Hopefully we'll stop getting quite so many pointless lint errors now :+1:
#127
=> Minor eslint changes

react-backend/client/src/components/admin/activitiesLib/activityHelpers.js, react-backend/client/src/components/admin/adminActivitiesPage.js
helper function updateId added again 
#127
=> adds undefined function that was accidentally removed by git 

react-backend/client/src/components/admin/adminActivitiesPage.js
Re-adds some error handling that was lost in a previous PR
Refactors error handling in adminActivitiesPage #127
=> Error handling in admin activities

package-lock.json, package.json, react-backend/client/package-lock.json, react-backend/client/package.json, react-backend/client/src/App.css, react-backend/client/src/components/admin/adminActivitiesPage.js, react-backend/client/src/components/admin/adminCBSettingsPage.js, react-backend/client/src/components/admin/adminUserDetailsPage.js, react-backend/client/src/components/visitors/main.js, react-backend/database/dbBuild.sql, react-backend/database/queries/CBqueries/getCBFromEmail.js, react-backend/database/queries/getCBDetails.js, react-backend/database/queries/putNewCBDetails.js, react-backend/functions/pdfgenerator.js, react-backend/routes/cb_details_new.js, react-backend/routes/cbauthentication/isAuthenticated.js, react-backend/routes/qr_generator.js, react-backend/routes/qr_send.js, react-backend/routes/qr_user_gen.js, react-backend/routes/qr_user_send.js, react-backend/routes/user_details_new.js
This pr relates to issue #125 
1. For uploading images I used 2 modules: react-dropzone and cloudinary, as was suggested in this article (you will need to do npm install for package.json in client folder): https://css-tricks.com/image-upload-manipulation-react/ 
The only thing that didn't work from this article was this code:
```
handleImageUpload(file) {
let upload = request.post(CLOUDINARY_UPLOAD_URL)
.field('upload_preset', CLOUDINARY_UPLOAD_PRESET)
.field('file', file);
```
But after some research I changed the code to this one:
```
handleImageUpload(file) {
const cloudinaryForm = new FormData();
cloudinaryForm.append('upload_preset', CLOUDINARY_UPLOAD_PRESET);
cloudinaryForm.append('file', file);
fetch(CLOUDINARY_UPLOAD_URL, {
method: 'POST',
body: cloudinaryForm,
headers: {
Accept: …
```
=> Uploading images

react-backend/client/src/App.css, react-backend/client/src/components/admin/adminUsersPage.js, react-backend/routes/cbauthentication/cb_register_check.js
#126
Small PR fixing the bar chart and some prettier stuff apparently
=> Made the bar chart usefully visible

.travis.yml, package.json
:upside_down_face: 🔪 👷 
- Add post-install script for lazy devs
- Kill travis (turn off success emails)
=> Tiny setup stuffs

.gitignore, react-backend/app.js, react-backend/client/src/components/admin/activitiesLib/admin_helpers.js, react-backend/client/src/components/admin/adminActivitiesPage.js, react-backend/client/src/components/admin/adminCBSettingsPage.js, react-backend/client/src/components/admin/adminUserDetailsPage.js, react-backend/client/src/components/admin/adminUsersPage.js, react-backend/client/src/components/admin/adminVisitsPage.js, react-backend/client/src/components/admin/admin_login.js, react-backend/client/src/components/authentication/logincb.js, react-backend/client/src/components/authentication/newPassword.js, react-backend/client/src/components/authentication/pswdresetcb.js, react-backend/client/src/components/authentication/signupcb.js, react-backend/client/src/components/visitors/main.js, react-backend/client/src/components/visitors/qrcode.js, react-backend/router.js
Fixes #189 
Fixes #173 
Potentially a messy fix for adding /api to all routes on the server, happy to manually add /api to all routes if peeps think this is better... 
And my prettier fucked a fair bit up 🙄...
Also I'm terribly out of practise of adding issue numbers to commit messages 🙈
=> Add /api routes

docs/README.md, docs/config_guide.md, docs/dev_setup_guide.md, package.json, react-backend/client/package.json
Fixes #198 
Related to #187 
I've started by adding a simple dev setup guide. I anticipate it (and in particular the config guide) will change significantly over the course of this phase, but it's good to have this to start with.
I also added all contributors to the `package.json`. Didn't know everyone's e-mail but can add them if you let me know what they are.
See my commits for a simple example of the kind of thing I was talking about in #188, in particular the multi-line messages, the fact that all changes in a commit are related, etc.
@astroash I'm sure you'll be happy to notice I'm using emoji. I'm using [gitmoji](https://kapeli.com/cheat_sheets/Gitmoji.docset/Contents/Resources/Documents/index) as the convention for emoji prefixes, not just prepending random ones. This helps quickly …
=> Docs dev setup

package-lock.json, package.json, react-backend/client/package-lock.json, react-backend/client/package.json, react-backend/client/src/components/authentication/logincb.js, react-backend/routes/cbauthentication/cb_login.js
Fixed the bug that was causing a 500 error whenever the input validation returned false. The res.send() was wrongly formatted and the error messages were backwards also.
Fixes #207
=> Fixed the 500 bug when input validation was false on cb login page

react-backend/app.js, react-backend/routes/cbauthentication/cb_login.js, react-backend/routes/cbauthentication/cb_password_change.js, react-backend/routes/cbauthentication/cb_password_reset.js, tests/routes_tests/cbauthentication_tests/cb_login.test.js, tests/routes_tests/cbauthentication_tests/cb_password_change.test.js, tests/routes_tests/cbauthentication_tests/cb_password_reset.test.js
- add test port in app
- add statusCodes for tested route
- create db queries for route testing
- add tape tests to check supertest expect errors
🤷‍♀️ not sure if this is best practise, I ended having to do a fair amount of db queries to be able to test routes
Also, I've not tested all the fail cases because the validation is painful and needs to be rewritten
relates #186
=> 👷‍♀️Test/api/cb/pwd/reset route

react-backend/database/database_clean.js, react-backend/database/database_rebuild.js, react-backend/database/queries/activities.js, react-backend/database/queries/activities_today.js, react-backend/database/queries/activity_add.js, react-backend/database/queries/activity_delete.js, react-backend/database/queries/activity_update.js, react-backend/database/queries/user_check_hash.js, react-backend/database/queries/user_details.js, react-backend/database/queries/user_details_update.js, react-backend/database/queries/users_all.js, react-backend/database/queries/users_chart_all.js, react-backend/database/queries/users_filtered.js, react-backend/database/queries/visitors_all.js, react-backend/database/queries/visitors_filtered.js
Remove redundant promise creations fro db queries
And switch out an object.assign
=> 🔥 Remove redundant promise creations fro db queries

docs/README.md, docs/users_outline.md
Outlines the 3 users in the app
fixes #234
=> 📝 Add info on different users in the app

react-backend/routes/visitor_name.js, tests/routes/admin_login.test.js, tests/routes/visitor_check.test.js, tests/routes/visitor_name.test.js
Added tests for /user/name-from-scan route
Added tests for /visit/check route 
Added tests for the /admin/login route
Relates #218 
***PR #237 MUST be merged first***
=> A few route tests [Built on #237]

docs/README.md, docs/architecture.md, docs/dev_checklist.md, docs/testing_guide.md
Fixes #212 
* Documents the developer checklist as discussed
* Documents the desired project architecture
=> Document dev checklist

db/schema.sql, docs/api_migration_plan.md, react-backend/client/src/components/admin/adminUserDetailsPage.js, react-backend/database/queries/user_details.js, react-backend/database/queries/user_details_update.js, react-backend/routes/user_details_update.js, tests/database/queries/user_details.test.js, tests/database/queries/user_details_update.test.js
Changed adminUserDetailsPage and its routes to be able to change a users phone number, email contact consent and sms contact consent.
Also had to change db query to stop it returning snake_case key names as dread lord linter had a bad experience with snakes and much prefers camels.
:snake: :camel: :snake: :camel: :snake: :camel: :snake: :camel: :snake: :camel: :snake: :camel: :snake: :camel: :snake: :camel: :snake: :camel: :snake: :camel: :snake: :camel: :snake: :camel: :snake: :camel: :snake: :camel: :snake: :camel: :snake:
=> Actually not so quick fix for props passed to user_details_update route

react-backend/client/src/api/index.js, react-backend/client/src/components/admin/admin_login.js
=> 🚨 Fix cbAdmin login missing token on header

react-backend/shared/controllers/__tests__/feedback.test.js, react-backend/shared/models/__tests__/cb-admin.test.js
In line with `jest` convention.
=> 🚐 Move tests to relevant folders

README.md, docs/README.md, docs/stack.md
* Remove old information & images from README
* Add documentation on project stack
=> 📝 update README

react-backend/client/src/App.js, react-backend/client/src/cb-admin/pages/Signup.js, react-backend/client/src/shared/components/form/LabelledInput.js, react-backend/client/src/shared/style_guide.js
These were changes that I wanted to include in the previous PR (#279), but it was merged before I could include them.
* The `region` field is set by the change handler anyway, but better to
pre-define it here, as it's more self-documenting.
* Comment API code back in
* Fix up error messages on form validation failure.
=> Additional updates to new CbSignupPage

react-backend/client/src/components/visitors/main.js, react-backend/routes/__tests__/qr.generator.test.js, react-backend/routes/qr_generator.js
- rename state.gender
- remove this.this.state
- rename smsing stuffs
fixes #282
=> 🐛 Fix signup issues #282

react-backend/client/src/cb-admin/pages/ConfirmPassword.js
- Get response data from result
- Wait for promise to resolve before redirecting
Fixes #315
=> 🐛 Fix admin ConfirmPassword comp

react-backend/client/src/cb-admin/pages/Login.js
=> Fix login bug from homepage

react-backend/client/src/App.js, react-backend/client/src/api/index.js, react-backend/client/src/cb-admin/components/DetailsTable.js, react-backend/client/src/cb-admin/components/QrBox.js, react-backend/client/src/cb-admin/pages/FeedbackPage.js, react-backend/client/src/cb-admin/pages/Settings.js, react-backend/client/src/cb-admin/pages/Visitor.js, react-backend/client/src/index.css, react-backend/client/src/shared/components/Dots.js, react-backend/client/src/shared/components/form/base.js, react-backend/client/src/shared/style_guide.js, react-backend/database/queries/__tests__/user_details.test.js, react-backend/database/queries/user_details.js, react-backend/routes/user_details.js
**MERGE #319 FIRST**
Visitor details page, including printable view. Deets in commits.
=> Visitor details page

react-backend/client/public/javascripts/instascan.js, react-backend/client/src/components/visitors/qrcode.js
I'm not sure if this is the whole problem solved, but I can't replicate the error...
- Add ref to div rather than grabbing from DOM
- Comment out iife as I _think_ its duplicate code
Fixes #325
=> 🐛 Fix instacam problems

react-backend/client/src/components/visitors/purposeButton.js, react-backend/client/src/components/visitors/thank_you_feedback.js, react-backend/client/src/components/visitors/thanks.js
**To be merged after #321**
Tiny PR
Fixes #328
=> Visitor thanks

react-backend/twine-admin/models/__tests__/twine-admin.test.js, react-backend/twine-admin/models/twine-admin.js
**NB: this was initially added as part of a dropped feature**
... but we will need this functionality for the next phase so I say let's get it in now 😊
- 🗃 Add query to get all cbs names with test
Relates #304
=> Add query to get all cb's names

.mailmap, react-backend/client/src/App.js, react-backend/client/src/cb-admin/components/TranslucentTable.js, react-backend/client/src/cb-admin/pages/VisitorDetails.js, react-backend/client/src/shared/components/layout/base.js, react-backend/database/queries/__tests__/visitors_all.test.js, react-backend/database/queries/visitors_all.js, react-backend/routes/activities_all.js, react-backend/routes/visitors_all.js
**MERGE #322 FIRST**
Visitor details page, not much changed.
=> Visitor details

react-backend/client/src/cb-admin/pages/Dashboard.js, react-backend/client/src/components/admin/adminUsersPage.js, react-backend/client/src/shared/components/form/DottedButton.js, react-backend/client/src/shared/components/form/base.js, react-backend/client/src/shared/components/text/base.js, react-backend/client/src/shared/pages/Home.js
**MERGE #323 FIRST**
Adds button component with the circles in the corners, CSS copied from the twine website, but translated to styled-components.
=> Button w/ circles

react-backend/client/src/cb-admin/pages/Activities.js
=> 🐛 Fix Activities page title and adding activities woes

react-backend/client/src/cb-admin/pages/Visitor.js, react-backend/database/queries/__tests__/user_details_update.test.js, react-backend/database/queries/user_details_update.js, react-backend/routes/user_details_update.js
Fixes broken visitor profile update feature
=> 🐛 fix visitor profile page

react-backend/client/src/api/index.js, react-backend/client/src/cb-admin/constants/error_text.js, react-backend/client/src/cb-admin/pages/Signup.js
=> 🐛 fix broken cb signup form

react-backend/client/src/cb-admin/pages/Activities.js, react-backend/client/src/shared/components/text/base.js, react-backend/database/queries/__tests__/activity_exists.test.js, react-backend/database/queries/activity_exists.js, react-backend/routes/activities_add.js
- Add query to check if it exists
- with tests
- Display error message on frontend
- Forward if any requests are made when admin token is expired
- Add error styled component to text base
Fixes #272
=> 🐛 Fix adding duplicate activities

docs/api_migration_plan.md, react-backend/client/src/api/index.js, react-backend/client/src/components/visitors/main.js, react-backend/client/src/components/visitors/signup_form.js, react-backend/router.js, react-backend/routes/cb_name_check.js
This makes the organisations name appear when a visitor is signing up.
Adds small route that just grabs from the middleware minor changes to main.js and signup_form.js
**Must be merged after #311.**
Fixes #274
=> Add OrgName to Visitor Signup

.github/PULL_REQUEST_TEMPLATE.md
Adding several sections to the developer checklist as reminders.
Also create a simple PR template and add this checklist to it.
Note: these wont all always be relevant, and sometimes the appropriate (or acceptable) answer to some of them will be "no". They are primarily intended as reminders and guidelines.
=> 📝 add PR template & update dev checklist

client/src/cb-admin/pages/Activities.js
**#344 to be merged first**
Totes not important, but...
I added a little fade to the error message on activities page.
=> Fade error

client/src/api/index.js, client/src/cb-admin/pages/VisitorDetails.js, docs/query_builder.md, package-lock.json, package.json, server/database/queries/__tests__/activities.test.js, server/database/queries/__tests__/user_details.test.js, server/database/queries/__tests__/user_details_update.test.js, server/database/queries/__tests__/users_all.test.js, server/database/queries/activity_update.js, server/database/queries/cb/cb_details_new.js, server/database/queries/user_details.js, server/database/queries/user_details_update.js, server/database/queries/users_all.js, server/routes/activities_update.js, server/routes/qr_user_send.js, server/routes/user_details_update.js, server/routes/users_all.js, server/shared/models/__tests__/query_builder.test.js, server/shared/models/query_builder.js
**Keen to get this reviewed/merged to avoid an ever growing dif**
Fixes #369 
Related to #363 
* edit query builder to make it more ridiculous
* change all routes which were using query builder
* fix related tests
* update visitors page to sort/filter using queries rather than frontend
=> 🗃 Update queryBuilder

client/src/cb-admin/pages/Signup.js, client/src/visitors/pages/homeVisitor.js
Fixes #391 #351 
* Just changes link location from `/logincb` to `/cb/login`
* Also removes logout link from visitors section 
Just a tiny little fix
=> Fixes wrong link on CB Signup page

client/src/cb-admin/pages/Visitor.js, client/src/shared/components/form/LabelledSelect.js, client/src/shared/components/form/base.js
Fixes #345, #348 
* Added arrow to LabelledSelect component.
* Changed yob on Visitor page to a select input.
_There's a lot of Prettier stuff inflating the diff_
=> Added dropdown arrows and yob field in Visitor page is now a select

server/routes/visitors_all.js
Fixes #409 
* changes column of cb_id that we're matching on. I've no idea why this fixes the bug, if anyone can explain that would be great and I'll add it to the docs
* Also changed the order to ascending so the most recent visits are at the bottom
* ~~[ ] Have I added a (set of) test(s) that proves the bug is fixed?~~
* ~~[ ] Have I documented any necessary developer notes/gotchas/lessons learnt from this bug fix?~~
=> 🐛 Fix error with missing visits data

README.md, client/public/index.html, client/public/manifest.json, docs/README.md, docs/architecture.md, docs/config_guide.md, docs/dev_setup_guide.md, package.json
Fixes #406 
* Changed all mention of Datapower to Twine or Twine Visitor App.
* Also changed references and URLs from FAC-11/DataPower to TwinePlatform/twine-visitor.
* Changed the email templates.
* _Will change the repo name when this is merged._
=> Changed all mention of DataPower to Twine or Twine Visitor App

package-lock.json, package.json, server/app.js
Fixes #410
* add `express-sslify`
~~* [ ] Is my new feature sufficiently well tested?~~
~~* [ ] Have I updated the project documentation and README to reflect my changes?~~
=> ⛑ Enforce https

server/functions/qr_send.js, server/functions/sendemail.js, server/routes/qr_generator.js, server/routes/qr_user_send.js
Fixes #432
* Postmark template already updated to accept new parameter.
=> 💬 add CB name to email template model object

docs/README.md, docs/database_backups.md
Fixes #428
Related to  TwinePlatform/data-sync#7
* schedule database backups on heroku and run local test restore
* document the above
=> 📝 Document database backup process

package.json, reporting/index.js
Related to TwinePlatform/hq#22
* Adds the two statistics Sonja asked for so far. 
Just run the newly added npm script. Test and dummy data is not filtered from the results.
=> 🗃 adds reporting script

server/routes/cbauthentication/__tests__/cb_register.test.js, server/routes/cbauthentication/cb_register.js
=> 🐛 Add region to joi validation cb/register

client/package-lock.json, client/src/api/index.js, client/src/cb-admin/pages/Dashboard.js, client/src/cb-admin/pages/Settings.js, client/src/cb-admin/pages/Visitor.js, client/src/cb-admin/pages/__tests__/Dashboard.test.js, client/src/cb-admin/pages/__tests__/Login.test.js, client/src/cb-admin/pages/__tests__/Settings.test.js, client/src/visitors/pages/main.js
- update cbAdmin.get
- remove deprecated route
- fix in components using this method
- create an axios instance for shared config
#473 <- kinda
=> 🌳 cb admin dashboard

client/src/api/index.js, client/src/cb-admin/pages/Activities.js, client/src/cb-admin/pages/__tests__/Activities.test.js, client/src/shared/components/form/LabelledSelect.js
~~**MERGE #475 first**~~
Fixes #476
=> Route cb activities

client/src/api/index.js, client/src/cb-admin/pages/Feedback.js, client/src/cb-admin/pages/__tests__/Feedback.test.js
Fixes #480
Related to #447 
* Update API call in api/index.js
* Update response processing code
* Add component test
=> ♻️ update cb-admin/Feedback page to work with new API

client/src/api/index.js, client/src/cb-admin/pages/__tests__/ConfirmPassword.test.js, client/src/visitors/pages/homeVisitor.js, client/src/visitors/pages/qrcode.js
Fixes #487 
Related to #447 
* Change URL
=> Confirm pwd

client/src/api/index.js, client/src/cb-admin/pages/Activities.js, client/src/cb-admin/pages/Feedback.js, client/src/cb-admin/pages/Settings.js, client/src/cb-admin/pages/Visitor.js, client/src/cb-admin/pages/VisitorDetails.js, client/src/cb-admin/pages/VisitsData.js, client/src/cb-admin/pages/__tests__/Settings.test.js, client/src/cb-admin/pages/__tests__/Visitor.test.js
Fixes #495
Related to #447 
* Fetch constants from endpoints instead of hardcoding them
* UX fixes to CB settings page
* Bug fixes to Activities and Feedback page
=> Fetch constants

client/src/api/index.js, client/src/cb-admin/pages/VisitsData.js
Fixes #482 
- update new routes
- manipulate responses to display graphs
=> 🌳 update visits page to support new api

client/src/cb-admin/pages/Settings.js, client/src/cb-admin/pages/__tests__/Visitor.test.js
Fixes #505
* Change to API SDK wasn't accounted for
=> 🐛 fix CSV export on settings page

client/src/api/index.js, client/src/cb-admin/pages/Activities.js, client/src/cb-admin/pages/Dashboard.js, client/src/cb-admin/pages/Feedback.js, client/src/cb-admin/pages/ForgotPassword.js, client/src/cb-admin/pages/ResetPassword.js, client/src/cb-admin/pages/Settings.js, client/src/cb-admin/pages/Visitor.js, client/src/cb-admin/pages/VisitsData.js, client/src/cb-admin/pages/__tests__/ForgotPassword.test.js, client/src/cb-admin/pages/__tests__/ResetPassword.test.js, client/src/cb-admin/pages/__tests__/Settings.test.js, client/src/cb-admin/pages/__tests__/Signup.test.js, client/src/visitors/pages/__tests__/homeVisitor.test.js, client/src/visitors/pages/homeVisitor.js, client/src/visitors/pages/main.js
Since some functions are related to the user (CbAdmin)
and some are related to the CB itself.
Fixes #507 
Fixes #510 
Fixes #491
See commit
=> ♻️ split CbAdmin API methods into CbAdmin/CommunityBusiness

client/src/App.js, client/src/api/index.js, client/src/cb-admin/pages/Login.js, client/src/cb-admin/pages/Visitor.js
Fixes #494 
Fixes #510
Related to #447
* See commits
=> Disable cb signup

.gitignore, client/.env, client/.env.development, client/.gitignore, client/src/api/index.js, client/src/cb-admin/pages/__tests__/Dashboard.test.js, client/src/cb-admin/pages/__tests__/Login.test.js
- add api url base as env variable
- NB clientside env vars not to be used for secrets so removed from .gitignore
Fixes #504
=> 🔧 add api url base as env variable

client/src/api/index.js, client/src/visitors/pages/__tests__/main.test.js, client/src/visitors/pages/main.js
**Changes**: send orgId when signing up new visitor
**Fixes** #516
NB: route is still not working due to TwinePlatform/twine-api#159
=> 🐛 send orgId when signing up new visitor

client/src/cb_admin/pages/Signup.js
- write comment as to why we have kept SignUp component
TwinePlatform/twine-api#97
=> 📝 comment unused SignUp

client/src/api/index.js, client/src/cb_admin/pages/ResetPassword.js, client/src/cb_admin/pages/__tests__/ResetPassword.test.js, server/routes/cbauthentication/__tests__/cb_password_change.test.js, server/routes/cbauthentication/cb_password_change.js, server/routes/cbauthentication/cb_password_reset.js
- fix cb password reset validation issues
- add more special characters to regex
- clarify error messages
- grab correct passwordConfirm from state for request
- update error utils to work with new api
=> Staging fix password reset

client/src/api/index.js, client/src/cb_admin/pages/__tests__/Login.test.js
Related to TwinePlatform/twine-api#170
* Update to use new login endpoint
=> ♻️ update to use new login route

client/src/visitors/pages/qrcode.js, server/routes/qr_generator.js
Related to #525 
* Forward to error page when there's an issue registering a visit
* Use `randomBytes` to (almost) guarantee unique hashes.
* ~~[ ] Have I added a (set of) test(s) that proves the bug is fixed?~~
=> Fix visit reg

client/src/visitors/pages/qrcode.js, server/routes/qr_generator.js
Related to #525 
* Same as #526, just porting to the staging branch
=> Fix visit reg 2

client/src/api/index.js
=> 🐛 rename ORG_ADMIN -> CB_ADMIN

src/api/index.js, src/cb_admin/components/QrBox.js, src/cb_admin/pages/Activities.js, src/cb_admin/pages/ConfirmPassword.js, src/cb_admin/pages/Dashboard.js, src/cb_admin/pages/Feedback.js, src/cb_admin/pages/ResetPassword.js, src/cb_admin/pages/Settings.js, src/cb_admin/pages/Visitor.js, src/cb_admin/pages/VisitorDetails.js, src/cb_admin/pages/VisitsData.js, src/cb_admin/pages/__tests__/ResetPassword.test.js, src/shared/components/form/DottedButton.js, src/shared/components/form/base.js, src/shared/components/text/base.js, src/shared/pages/Home.js, src/visitors/components/purposeButton.js, src/visitors/components/signup_form.js, src/visitors/pages/homeVisitor.js, src/visitors/pages/main.js, src/visitors/pages/qrcode.js
**Changes:**
- Homepage makes api call to redirect to login if no cookie is present
- get base url from node environment
- redirect to correct page for qr code errors
- update pw forgot/reset to work with new api
- add redirect payload to forgot
- add email to reset
=> 🐛 Fix homepage && password pages

src/shared/pages/Home.js, src/visitors/pages/__tests__/homeVisitor.test.js, src/visitors/pages/__tests__/main.test.js, src/visitors/pages/homeVisitor.js, src/visitors/pages/main.js, src/visitors/pages/qrcode.js
=> 🐛 deescalate login on all main visitor routes

src/shared/pages/Home.js, src/visitors/pages/homeVisitor.js, src/visitors/pages/main.js, src/visitors/pages/qrcode.js
=> 🐛 fix de-escalations by adding `catch` to them all

src/cb_admin/pages/Feedback.js, src/cb_admin/pages/VisitorDetails.js, src/cb_admin/pages/VisitsData.js, src/util.js, src/visitors/pages/qrcode.js
Fixes #459
Related to #562
* Just comment out the relevant stuff for now.
* Change styling back so that `<video>` is 100% of container width, and revert copy.
=> 💩 comment out the signup-with-name feature for now

.gitignore, app.json, docs/config_guide.md, package-lock.json, package.json, src/api/index.js
- remove unused module
- update heroku pipeline config
- update docs
Fixes #561 
Changes made on heroku for this pr:
- remove all old env vars from when app was fullstack
- review apps get env vars from staging
Review app here: https://twine-visitor-staging-pr-570.herokuapp.com/
=> 🔧 set base url from env vars

src/visitors/pages/qrcode.js, src/visitors/pages/qrerror.js
* Attempts to address #594 by detecting if `Instascan` is available
=> prevent crash in absence of Instascan

src/cb_admin/pages/Login.js, src/cb_admin/pages/__tests__/Login.test.js
=> 🐛 display error message on login for 403

app.json, index.js, src/api/index.js
=> 🐛 remove version num from proxy

package-lock.json, package.json, src/shared/pages/Home.js
- that horrid login page flash when no cookie is present 
* install react-spinners
* display spinner whilst waiting for cookie validation on homepage
=> ✨ add spinner to homepage

src/cb_admin/pages/VisitsData.js
Fixes #612 
* Update graph titles
NB: Only making pr to master as it's copy change
=> 🐛 Clarify visit graph titles

src/cb_admin/components/QrBox.js, src/cb_admin/pages/Visitor.js
Related to TwinePlatform/twine-api#298
* track state or resendQrCode request
- display error message if error is returned
Linked to PR:
https://github.com/TwinePlatform/twine-api/pull/300
=> 🐛 fix error resendQrCode for users with null email

src/cb_admin/pages/Dashboard.js, src/cb_admin/pages/Feedback.js
* Dashboard left nav link points to home page instead of logout (Fixes #575)
* Feedback logout link removed (Fixes #576)
=> Update navigation links

src/cb_admin/pages/ResetPassword.js
=> 🚸 update how component inspects error message

src/visitors/index.js
Fixes #622
* `exact path` was causing the `Signup` component to unmount and mount due to the path change. Changed to `path`.
- also added a Fragment cos dunno how that was even working without one
=> 🐛 missing qr code due to state reload

src/cb_admin/pages/Activities.js, src/cb_admin/pages/Dashboard.js, src/cb_admin/pages/Feedback.js
**MERGE #615 FIRST**
Fixes #617
* Use `redirectOnError` on Activities page
=> Fix activities page 403

src/visitors/pages/Signup.js
Fixes #622
* Fix NEXT link on signup page
=> 🐛 fix link

src/cb_admin/pages/ResetPassword.js
Fixes #629
Relates to user testing of #628 
* fixes duplicated pw strength error on pw reset
=> 🐛 fixes duplicated pw strength error on pw reset

src/api/index.js, src/cb_admin/pages/Activities.js, src/cb_admin/pages/Dashboard.js, src/cb_admin/pages/Feedback.js, src/cb_admin/pages/Visitor.js, src/cb_admin/pages/VisitorDetails.js, src/cb_admin/pages/VisitsData.js, src/cb_admin/pages/__tests__/Activities.test.js, src/cb_admin/pages/__tests__/Dashboard.test.js, src/cb_admin/pages/__tests__/Visitor.test.js, src/cb_admin/pages/__tests__/VisitorDetails.test.js
Related to #634
* Hacky fix for redirect on full admin access routes
- log into visitor app
- manually go to a `/cb/...` route
- every page should redirect to `ConfirmPassword` page
=> Fix full cookie restriction

src/api/index.js, src/cb_admin/pages/Activities.js, src/cb_admin/pages/Dashboard.js, src/cb_admin/pages/Feedback.js, src/cb_admin/pages/Visitor.js, src/cb_admin/pages/VisitorDetails.js, src/cb_admin/pages/VisitsData.js, src/cb_admin/pages/__tests__/Activities.test.js, src/cb_admin/pages/__tests__/Dashboard.test.js, src/cb_admin/pages/__tests__/Visitor.test.js, src/cb_admin/pages/__tests__/VisitorDetails.test.js
Repeat of #636 
Staging has been hard reset.
PR to be squashed and merged
=> 🔂 REPEAT - Fix full cookie restriction

src/api/index.js, src/cb_admin/pages/Activities.js, src/cb_admin/pages/ConfirmPassword.js, src/cb_admin/pages/Dashboard.js, src/cb_admin/pages/Feedback.js, src/cb_admin/pages/Settings.js, src/cb_admin/pages/Visitor.js, src/cb_admin/pages/VisitorDetails.js, src/cb_admin/pages/VisitsData.js, src/shared/components/NavHeader.js, src/shared/pages/Home.js, src/visitors/components/signup_form.js, src/visitors/pages/Signup.js, src/visitors/pages/__tests__/Signup.test.js, src/visitors/pages/homeVisitor.js, src/visitors/pages/qrcode.js
Standard User Flows:
Additional things/user flows to test:
Partnered PR: TwinePlatform/twine-api#320
=> 🚀 DEPLOYMENT 28-01-19

src/api/index.js, src/cb_admin/pages/Activities.js, src/cb_admin/pages/ConfirmPassword.js, src/cb_admin/pages/Dashboard.js, src/cb_admin/pages/Feedback.js, src/cb_admin/pages/Settings.js, src/cb_admin/pages/Visitor.js, src/cb_admin/pages/VisitorDetails.js, src/cb_admin/pages/VisitsData.js, src/shared/components/NavHeader.js, src/shared/pages/Home.js, src/visitors/components/signup_form.js, src/visitors/pages/Signup.js, src/visitors/pages/__tests__/Signup.test.js, src/visitors/pages/homeVisitor.js, src/visitors/pages/qrcode.js
=> 🚀 DEPLOYMENT 30-01-19

package.json, src/cb_admin/pages/__tests__/Activities.test.js, src/cb_admin/pages/__tests__/ConfirmPassword.test.js, src/cb_admin/pages/__tests__/Dashboard.test.js, src/cb_admin/pages/__tests__/Feedback.test.js, src/cb_admin/pages/__tests__/ForgotPassword.test.js, src/cb_admin/pages/__tests__/Login.test.js, src/cb_admin/pages/__tests__/ResetPassword.test.js, src/cb_admin/pages/__tests__/Settings.test.js, src/cb_admin/pages/__tests__/Signup.test.js, src/cb_admin/pages/__tests__/Visitor.test.js, src/cb_admin/pages/__tests__/VisitorDetails.test.js, src/tests/index.js, src/tests/mock_instascan.js, src/tests/mock_responses.js, src/visitors/pages/__tests__/Signup.test.js, src/visitors/pages/__tests__/homeVisitor.test.js
Related to #653 
* Add utility for mocking HTTP API calls
* Add simple mock for Instascan library
=> ✅ add mock responses functions and mock Instascan interface

src/visitors/components/FeedbackButtons.js, src/visitors/pages/homeVisitor.js
also styling and copy improvements
Related to #653 
* Extract feedback buttons component
* Use flexbox to style `homeVisitor`
* Update copy on buttons on `homeVisitor`
=> ♻️ extract feedback buttons

src/cb_admin/components/TranslucentTable.js, src/cb_admin/pages/Dashboard.js
* Properly align/center the dashboard buttons
* add "cursor: pointer" to table rows if clickable
Fixes #667
=> 💄 Improve dashboard layout

src/cb_admin/pages/VisitsData.js
* Prevent crash on choosing null age filter
* Fix API call so that filters actually work
* Update response payload processing to get correct CSV data
* Update filename
Fixes #666 
Paired with TwinePlatform/twine-api#337
Additional user flows to test:
=> 🐛 fix visits export

src/visitors/pages/qrcode.js
Fixes #671
Related to #665
* Add a message and a back button when there are no activities
=> 🐛 display message when no activities scheduled

docs/README.md, docs/dev_notes.md, docs/user_testing_guide.md
Currently docs just link to issues, but once those questions/flows are nailed down, we can document them here or somewhere appropriate.
=> 📝 add initial pass of user testing instructions
